### PR TITLE
fix(impersonatedUser): get user e-mail from profile instead authentic…

### PR DESCRIPTION
**Pull request by ygorneves10**
**What problem is this solving?**
When use the telemarketing app to impersonate an user. The app is using the seller data, instead customer data.

**How should this be manually tested?**
[workspace](https://ygorneves--hermespardini.myvtex.com/)

### CODE REVIEW

**Comment by ygorneves10** [comment]
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

**Comment by polishq** [comment]
@ygorneves10 Can you explain about your use case?

This was an intentional decision that we made, that when impersonating a user, your original permissions should still be respected. For example, if you have permissions to place an order but the impersonated user does not, you should still be able to place an order when impersonating. 

Perhaps we should make the logic a little more sophisticated, such as joining the permissions of the original user and the impersonated user. If you can let us know how you're expecting impersonation to work, that would be helpful.

**Comment by ygorneves10** [comment]
@polishq we're developing a b2b e-commerce where the customer are not able to see the prices without login and respective permission. So in this case, the seller who is logged in, is not allowed to see prices and place an order, but the customer who has been impersonated, has this permission. That's why we need to consider the customer permissions.

**Comment by polishq** [comment]
Support for telesales impersonation was added in PRs https://github.com/vtex-apps/storefront-permissions/pull/39 and https://github.com/vtex-apps/storefront-permissions/pull/40 👍

**Pull request closed without merging**
